### ISSUE TITLE
Add RS-232 input to Ethernet switch board

### ISSUE THREAD

**Issue by thanasipantazides** [foxsi/UMN-boards-FOXSI-4#1]
### Need:

To uplink commands from TM section (over RS-232 TX line) to Raspberry Pi.

### Todo:

- [x] Find an RS-232 <=> UART translator (with some memory, no fancy interrupting/flow control stuff)
- [x] Identify appropriate Raspberry Pi UART to route command uplink into.
- [x] Add that chip to the Ethernet switch, bottom side.
